<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Hi ' => '',
    'All the best - ' => '',
    'And let\'s just keep this between you and me.' => '',
    'And yet again - WELCOME to KidUp!' => '',
    'Check it out at this link: ' => '',
    'Excited greetings,' => '',
    'Have you planed a pickup destination and time yet? Otherwise you guys should write each other and plan!' => '',
    'Hi ' => '',
    'Hope that you had a pleasant experience and feel free to contact me.' => '',
    'How is that for a good piece of news? You are now ready to contact {user} and plan a pickup time and adress.' => '',
    'I am just writing to you to check up on the new emailadress you registered on KidUp.' => '',
    'I heard you lost your password, do not worry! I found it.' => '',
    'I just checked with your accountant and the payment went through!' => '',
    'If any problems occur, do not hestitate to mail me at ' => '',
    'If there is anything, maybe you just want to tell me a story, then write me at : ' => '',
    'If you haven\'t ordered that the KidUp user should chance into this mailadress, just leave this mail behind.' => '',
    'If you like to respond to <strong>{user}</strong> then please follow this link:' => '',
    'If you plan on returning it, remember to plan with {owner} for a place to deliver it back!' => '',
    'If you\'d like to stop the rent, remember to contact {renter} to agree on a delivery time!' => '',
    'If your basement is filled with unused kidsstuff you can also rent it out here, so other parents - almost as sweet
    as you - can benefit from it!' => '',
    'Is this it? If I miraculously got it right then yay me. Oh and please click ' => '',
    'It seems to me that you\'re happy with it, if so you could consider contacting
            <strong>{owner}</strong> to hear if {owner, select, female{she} male{he} other{(s)he}}
            would like to rent it out again.' => '',
    'It seems to me that {renter} is happy with it, you could consider contacting
            <strong>{renter}</strong> to hear if {renter, select, female{she} male{he} other{(s)he}}
            would like to rent it from you again.' => '',
    'It\'s me, {0}. I just wanted to let you know that there is under 48 hours until the rent of <strong>{1}</strong>
    expires.' => '',
    'Just to let you know, the rent for <strong>{0}</strong> has changed into status<strong>{1}</strong>.' => '',
    'KidUp recovery' => '',
    'KidUp user {0} wants to rent your item!' => '',
    'Kidup email confirmation' => '',
    'Kidup email reconfirmation' => '',
    'Kidup payment confirmation' => '',
    'Kidup: one of your rents changed' => '',
    'Kidup: one of your rents is about to end' => '',
    'Kidup: one of your rents is about to start' => '',
    'Lots of Love' => '',
    'Lots of Love,' => '',
    'Lots of Love, ' => '',
    'Lots of love,' => '',
    'Lots of love, ' => '',
    'Maybe you want to rent some stuff for your sweet children? You can do that here:' => '',
    'Oh, and you can directly confirm this email adress by clicking this link: ' => '',
    'There has been quite the activity in your chat, actually <strong>{0}</strong> people wrote you during the last day.' => '',
    'We are glad that you are using KidUp, if you would like to, you could share your love for sharing (silly eh\') on
    Facebook!' => '',
    'We are so excited to let you know that the rent of the item <strong>{item}</strong>
            from <strong>{owner}</strong> to you is about to start!' => '',
    'We are so excited to let you know that the renting of your item <strong>{item}</strong>
            to <strong>{renter}</strong> is about to start!' => '',
    'Welcome to KidUp, I am so glad that you joined us and cannot wait to let you use our service!' => '',
    'You can do that, just by pressing this link: ' => '',
    'You can recover it by visiting' => '',
    'You have {0} unread messages at KidUp' => '',
    'Your item {0} has been seen by a lot of people and one of them, <strong>{1}</strong>, decided to ask
    to rent it.' => '',
    'create new item' => '',
    'here.' => '',
    '{user} would like to rent if from <strong>{date_from, date}</strong>till <strong>{date_to, date}</strong> which would give
    you a total of <strong>{amount, number}.</strong> You can learn more about {user} ' => '',
    'Check it out at {0}.' => '@@@@',
    'Welcome to KidUp!' => '@@@@',
];
