<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About our company' => '',
    'Account settings' => '',
    'Chat' => '',
    'Complete your registration' => '',
    'Confirm Your Rent' => '',
    'Confirm your telephone' => '',
    'Connect your account to {0}' => '',
    'Contact us' => '',
    'Email settings' => '',
    'Error' => '',
    'Frequently asked questions' => '',
    'How do payments work' => '',
    'How to rent from other parents' => '',
    'How to rent to other parents' => '',
    'Item Availability' => '',
    'Item Details' => '',
    'Item Prices' => '',
    'Item Rents' => '',
    'Item images' => '',
    'KidUp guides' => '',
    'Kidup user {0}' => '',
    'Launching soon' => '',
    'List Your Rents' => '',
    'Location Settings' => '',
    'Log In' => '',
    'My items list' => '',
    'Online parent-to-parent marketplace' => '',
    'Privacy' => '',
    'Profile settings' => '',
    'Profile verification' => '',
    'Recover your password' => '',
    'Resend confirmation email' => '',
    'Safety' => '',
    'Share Kid Stuff' => '',
    'Sign up' => '',
    'Terms and conditions' => '',
    'Thank you for signing up' => '',
    'View For Item {0}' => '',
    'Why use kidup' => '',
    'Your kidup wallet' => '',
    'reset your password' => '',
    '{0}' => '',
    '{0} KidStuff' => '',
];
