#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_CONSOLE') or define('YII_CONSOLE', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));


require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');
if(is_file(__DIR__ . '/config/config-local.php')){
    $config = yii\helpers\ArrayHelper::merge($config, require(__DIR__ . '/config/config-local.php'));
}

$application = new yii\console\Application($config);

if(\Yii::$app->keyStore->get('environment') == 'dev'){
    \Yii::$app->urlManager->setHostInfo('http://192.168.33.99');
    \Yii::setAlias('@web', Yii::$app->urlManager->getHostInfo().'/web');
}else{
    \Yii::$app->urlManager->setHostInfo('http://beta.kidup.dk');
    \Yii::setAlias('@web', Yii::$app->urlManager->getHostInfo());
}
Yii::setAlias('@assets', Yii::getAlias('@web').'/assets_web');
if (YII_ENV == 'test') {
    Yii::setAlias('@web', Yii::getAlias('@web').'/index-test.php');
}
if (YII_ENV == 'test' || YII_ENV == 'dev') {
    Yii::$app->language = 'en-US';
}
// set the locale for Carbon
\Carbon\Carbon::setLocale(Yii::$app->language[0].\Yii::$app->language[1]);
setlocale(LC_TIME, str_replace('-', '_', Yii::$app->language));
$exitCode = $application->run();
exit($exitCode);
