<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii kidup-message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Carseat' => 'Autosæde',
    'Room' => 'Værelse',
    'Stroller' => 'Barnevogn',
    '1-2 years' => '1-2 år',
    '2-4 years' => '2-4 år',
    '4-6 years' => '4-6 år',
    '6-12 months' => '6-12 måneder',
    '6-9 years' => '6-9 år',
    '9+ years' => '9+ år',
    '< 6 months' => '< 6 måneder',
    'Bikes' => 'Cykler',
    'Clothing' => 'Tøj',
    'Cribs & Beds' => 'Krybber & Senge',
    'Electronic' => 'Elektronik',
    'Furniture' => 'Møbler',
    'Other' => 'Andre',
    'Outdoor' => 'Udendørs',
    'Packages' => 'Pakker',
    'Parents' => 'Forældre',
    'Pet-free home' => 'Kæledyrsfrit hjem',
    'Safety' => 'Sikkerhed',
    'Safety Seats' => 'Autosæder',
    'Sports & Games' => 'Sport og leg',
    'Strollers' => 'Barnevogne',
    'Toys' => 'Legetøj',
    'Travelling' => 'Rejsende',
    'name' => 'navn',
];
