<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Approved by Experts' => '',
    'Become a part of the KidUp familiy' => '',
    'But at KidUp you can rent it. Then together you can find out, if it\'s really truly something.' => '',
    'By renting products from other parents, you\'re sure to get picture perfect experthelp.<br>So you can focus on being a good parent.' => '',
    'Choose and rent' => '',
    'Find Kids stuff' => '',
    'Find the things which fits your family' => '',
    'I am completely in love with the sharing-aspect and think it makes perfect sence to share things you aren\'t raelly using.' => '',
    'Meet and share' => '',
    'Meet other families and share experiences related to the rented product.' => '',
    'Review and Help' => '',
    'Review your experience, so other KidUppers can easily and swithfly find the right item.' => '',
    'Seek and Find' => '',
    'Sign Up Now' => '',
    'Together we can teach our children to share and reuse.' => '',
    'Understand how simple it is to use KidUp?' => '',
    'We can help other families' => '',
    'With KidUp you can easily seek and find the products to help your family.' => '',
    'With the money we make on renting Vilhelm\'s equipment out, we can take a summertrip to Legoland with the entire family.' => '',
    'You can quickly explore, see prices, see pictures and rent products through KidUp.' => '',
    'You cannot have everything' => '',
    'Share a' => 'Del en',
    'a stroller,a toy,a bike' => 'en barnevogn, et lejetøj, en cykel',
    'stroller,toy,bike' => 'barnevogn,legetøj,cykel',
    'trolley' => 'barnevogn',
    'How to use kidup?' => 'Hvordan bruger du KidUp?',
    'KidUp is your online parent-to-parent marketplace.' => 'KidUp er din online forældre til forældre markedsplads',
    'Share' => 'Del',
    'Share the world' => 'Del verdenen',
    'With a family near you' => 'Med en familie nær dig',
    'a trolley' => 'En løbevogn',
];
