<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Share a' => 'Del en',
    'stroller,toy,bike' => 'barnevogn,leget&oslash;j,cykel',
    'trolley' => 'barnevogn',
    'How to use kidup?' => 'Hvordan bruger du KidUp?',
    'KidUp is your online parent-to-parent marketplace.' => 'KidUp er din online for&aelig;ldre til for&aelig;ldre markedsplads',
    'Share' => 'Del',
    'Share the world' => 'Del verdenen',
    'With a family near you' => 'Med en familie n&aelig;r dig',
    'a stroller,a toy,a bike' => 'en barnevogn, et lejet&oslash;j, en cykel',
    'a trolley' => 'En l&oslash;bevogn',
];
