<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii kidup-message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'KidUp Booking' => '',
    'No results, perhaps try Stroller, Trampoline or Toy?' => '',
    'We couldn\'t find that, perhaps try Stroller, Trampoline or Toy?' => '',
    'e.g. {0}' => '',
    'Become a part of the KidUp familiy' => 'Bliv en del af KidUp familien',
    'I am completely in love with the sharing-aspect and think it makes perfect sence to share things you aren\'t raelly using.' => 'Jeg er fuldstændig forelsket med deleaspektet og synes det giver god mening at dele de ting vi alligevel ikke bruger heletiden.',
    'Share a' => 'Del en',
    'Sign Up Now' => 'Register dig nu',
    'With the money we make on renting Vilhelm\'s equipment out, we can take a summertrip to Legoland with the entire family.' => 'De penge vi får ved at leje Vilhelms ting ud kan vi bruge på en sommertur til Legoland med hele familien.',
    'stroller,toy,bike' => 'barnevogn,legetøj,cykel',
    'trolley' => 'barnevogn',
    'Approved by Experts' => 'Godkendt af Eksperter',
    'But at KidUp you can rent it. Then together you can find out, if it\'s really truly something.' => 'Men hos KidUp kan du leje det. Og så kan i sammen finde ud af om det virkelig er noget.',
    'By renting products from other parents, you\'re sure to get picture perfect experthelp.<br>So you can focus on being a good parent.' => 'Ved at leje produkter af andre familier er du sikker på at få den helt rette eksperthjælp.',
    'Choose and rent' => 'Lej sikkert',
    'Find Kids stuff' => 'Find børneudstyr',
    'Find the things which fits your family' => 'Find de ting som passer til din familie',
    'How it Works' => 'Sådan virker det',
    'How to use kidup?' => 'Sådan bruger du KidUp',
    'I am completely in love with the sharing-aspect and think it makes perfect sense to share things you aren\'t using at the moment.' => 'Jeg er fuldstændig forelsket med deleaspektet og synes det giver god mening at dele de ting vi alligevel ikke bruger hele tiden.',
    'KidUp Search' => 'KidUp Søg',
    'KidUp is your online parent-to-parent marketplace.' => 'KidUp er din online forældre til forældre markedsplads',
    'Meet and share' => 'Hjælp hinanden',
    'Meet other families and share experiences related to the rented product.' => 'Lad dine børneting hjælpe andre, og fortæl om de gode oplevelser til andre.',
    'Review and Help' => 'Anmeld og hjælp',
    'Review your experience, so other KidUppers can easily and swithfly find the right item.' => 'Anmeld din oplevelse så andre KidUppere nemt og hurtigt kan finde det rigtige børneudstyr.',
    'Search' => 'Søg',
    'Seek and Find' => 'Find Udstyr',
    'Share' => 'Del',
    'Share the world' => 'Del verdenen',
    'Together we can teach our children to share and reuse.' => 'Sammen kan vi lære vores børn at dele og genbruge.',
    'Understand how simple it is to use KidUp?' => 'Find ud af hvor simpelt det er at bruge KidUp',
    'We are honered to be featured on' => 'Vi er stolte af at være nævnt i',
    'We can help other families' => 'Forældre elsker KidUp',
    'What are you looking for?' => 'Hvad kigger du efter?',
    'What do you like to get your child?' => 'Hvad leder du efter til dit barn?',
    'With KidUp you can easily seek and find the products to help your family.' => 'Hos KidUp finder du nemt lige det børneudstyr, du har brug for, i nærheden af dig.',
    'With a family near you' => 'Med en familie nær dig',
    'With the money we made on Kidup with Vilhelm\'s unused equipment, we can take a summertrip to Legoland with the entire family.' => 'De penge vi får ved at leje Vilhelms ting ud kan vi bruge på en sommertur til Legoland med hele familien.',
    'You can quickly explore, see prices, see pictures and rent products through KidUp.' => 'Kidup er en sikker platform at leje igennem – vi garanterer sikker betaling og forsikrer dine ting.',
    'You cannot have everything' => 'Du kan ikke få alt',
    'a stroller,a toy,a bike' => 'en barnevogn,et lejetøj,en cykel',
    'a trolley' => 'En løbevogn',
];
