<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File format not allowed' => 'Filformatet er ikke tilladt',
    'KidUp is about larger items, like strollers, cribs, alarmsystems etc.
                                                 If you can only supply a small item, you can combine those in the age-packages.' => 'KidUp henvender sig til større ting, såsom barnevogne, vugger,
alarmsystemer etc. Har du mindre ting, f.eks. tøj, kan du samle det i
alderskasser.',
    'Kidup is about trust too. If you see a personal
                                                description of different things, it gives credibility. Trust and personality is the essence of KidUp' => '',
    'The terms and conditions have to be accepted before an item can be published' => 'KidUp handler også om tillid. Hvis man ser personlig beskrivelse af de
forskellige ting, så får man ro i maven. Det giver troværdighed og
tillid.',
    'To rent and rent out is about seeing what we are truly renting.
                                                In other words KidUp is about taking really good pictures.' => 'At leje og udleje ting handler om, at vi virkelig kan se hvad vi lejer.
På KidUp handler det altså om, at du tager nogle knaldgode billeder.',
    'Apply filter' => 'Tilføj filter',
    'Back' => 'Tilbage',
    'Choose a filter' => 'Vælg et filter',
    'Close' => 'Luk',
    'Distance: ' => 'Distance:',
    'KidUp is about larger items, like strollers, cribs, alarmsystems etc.
                                                 If you can only supply a small item, you can combine those in the age-packages.' => 'KidUp henvender sig til større ting, såsom barnevogne, vugger,
alarmsystemer etc. Har du mindre ting, f.eks. tøj, kan du samle det i
alderskasser.',
    'Kidup is about trust too. If you see a personal
                                                description of different things, it gives credibility. Trust and personality is the essence of KidUp' => 'KidUp handler også om tillid. Hvis man ser personlig beskrivelse af de
forskellige ting, så får man ro i maven. Det giver troværdighed og
tillid.',
    'Please provide some high quality pictures of your product.' => 'Vær venlig at uploade nogle høj kvalitets billeder af dit produkt.',
    'Refresh the page if eveyrhting is fixed.' => 'Opdater siden hvis alt er ordnet.',
    'To rent and rent out is about seeing what we are truly renting.
                                                In other words KidUp is about taking really good pictures.' => 'At leje og udleje ting handler om, at vi virkelig kan se hvad vi lejer.
På KidUp handler det altså om, at du tager nogle knaldgode billeder.',
    'items' => 'ting',
    'preferred payout method' => 'ønskede udbetalingsmetode',
    'Active filters:' => 'Aktive filtre',
    'Add some quality pictures of your product.' => 'Tilføj nogle kvalitetsbilleder af dit produkt',
    'Age' => 'Alder',
    'Ages' => 'Alder',
    'An item needs atleast one image.' => 'Et produkt skal bruge mindst et billede.',
    'Anything special about this product?' => 'Noget specielt ved produktet?',
    'Apply Filters' => 'Tilføj filtre',
    'As good as new' => 'Så god som ny',
    'Bookings' => 'Bookinger',
    'By publishing an item, you agree with our terms and conditions.' => 'Ved at offentliggøre et produkt er du enig med vores Terms and Conditions',
    'Categories' => 'Kategorier',
    'Chat' => 'Chat',
    'Clear' => 'Ryd',
    'Condition' => 'Stand',
    'Create Listing' => 'Lav en listing',
    'Create a new item' => 'Opret et produkt',
    'Description' => 'Beskrivelse',
    'Drag and drop images or click the box to start uploading. They can be sorted by dragging uploaded pictures, the first picture will be used as \'billboard\' image on the product page.' => 'Træk og smid billeder eller klik på kassen for at starte med at uploade. Du kan sortere dine billeder ved at trække uploade billeder rundt. Det første billede bliver dit hovedbillede.',
    'Edit' => 'ændre',
    'Filter' => 'Filter',
    'Filters' => 'Filtre',
    'Having trouble setting the right price for your product? We can suggest one if you know the new price of the item:' => 'Har du problemer med at sætte den rigtige pris for dit produkt? Vi kan foreslå dig ind baseret på nyprisen:',
    'How can you describe your item, in one catchy title?' => 'Hvordan kan du beskrive tingen i en fangende titel?',
    'How much is the item used? What do you enjoy so much about it? What parent-child moments did you experience with this item?' => 'Hvor brugt er udstyret? Hvor glad er du for det? Har du nogle gode historier med det?',
    'Lightly damaged' => 'Mere brugt',
    'Listings' => 'Listings',
    'Location' => 'Lokalitet',
    'Manage the item you\'d like to share with other families' => 'Få styr på de ting du vil dele med andre familier',
    'Minor usage trails' => 'Mindre brugsspor',
    'New price in DKK' => 'Nypris i DKK',
    'Only the weekly price is required.' => 'Kun den ugentlige pris behøves.',
    'Pending Requests' => 'Afventende anmodning',
    'Per day' => 'Per dag',
    'Per month' => 'Per måned',
    'Per week' => 'Per uge',
    'Pictures' => 'Billeder',
    'Please complete your {0}.' => 'Færdiggør venligst din {0}.',
    'Please set your location in your {0}.' => 'Vær venlig at sætte din lokalitet i dine {0}.',
    'Preview & Publishing' => 'Se og publiser',
    'Price' => 'Pris',
    'Price (Weekly)' => 'Ugentlig pris',
    'Price suggestions' => 'Pris forslag',
    'Pricing info' => 'Prisinformation',
    'Product info' => 'Produkt info',
    'Publish' => 'Publiser',
    'Publish date' => 'Dato for publisering',
    'Published' => 'Publiseret',
    'Receive date' => 'Afhentningsdato',
    'Refresh the page if everything is fixed.' => 'Opdater siden hvis alt er ordnet.',
    'Rented by {0} between {1} and {2}' => 'Lejet af {0} mellem {1} og {2}',
    'Respond' => 'Responder',
    'Return date' => 'Afleveringsdato',
    'Search' => 'Søg',
    'Special' => 'Special',
    'There are some things left to be fixed before you can preview or publish this item.' => 'Der er nogle få ting tilbage som skal fikses før du kan se eller publisere denne ting.',
    'This is a list of your published and unpublished listings' => 'Dette er en liste af dine publiseret og ikke publiseret ting.',
    'This is a preview. Go here {0} to publish this item.' => 'Dette er en prøve. Gå her {0} for at publisere.',
    'Title' => 'Titel',
    'Unpublish' => 'Upublicer',
    'Unpublished' => 'Upubliceret',
    'View' => 'Se',
    'What are you looking for?' => 'Hvad kigger du efter?',
    'What categories describe your item best?' => 'Hvilken kategori beskriver bedst tingen?',
    'Which ages is this product ment for?' => 'Hvilke aldre er dette produkt tiltænkt?',
    'day' => 'dag',
    'link' => 'link',
    'location settings' => 'lokalitetsindstillinger',
    'month' => 'måned',
    'profile' => 'Profil',
    'step 1 out of 2' => 'Skridt 1 ud af 2',
    'step 2 out of 2' => 'Skridt 2 ud af 2',
    'week' => 'uge',
];
