<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add some quality pictures of your product.' => '',
    'Apply filter' => '',
    'As good as new' => '',
    'Back' => '',
    'Choose a filter' => '',
    'Close' => '',
    'Lightly damaged' => '',
    'Minor usage trails' => '',
    'Price (Weekly)' => '',
    'Refresh the page if eveyrhting is fixed.' => '',
    'Please provide some high quality pictures of your product.' => '@@V&aelig;r venlig at uploade nogle h&oslash;j kvalitets billeder af dit produkt.@@',
    'preferred payout method' => '@@&oslash;nskede udbetalingsmetode@@',
    'Age' => 'Alder',
    'Ages' => 'Alder',
    'An item needs atleast one image.' => 'Et produkt skal bruge mindst et billede.',
    'Anything special about this product?' => 'Noget specielt ved produktet?',
    'Bookings' => 'Bookinger',
    'By publishing an item, you agree with our terms and conditions.' => 'Ved at offentligg&oslash;re et produkt er du enig med vores Terms and Conditions',
    'Categories' => 'Kategorier',
    'Chat' => 'Chat',
    'Clear' => 'Ryd',
    'Condition' => 'Stand',
    'Create Listing' => 'Lav en listing',
    'Create a new item' => 'Opret et produkt',
    'Description' => 'Beskrivelse',
    'Distance: ' => 'Distance:',
    'Drag and drop images or click the box to start uploading. They can be sorted by dragging uploaded pictures, the first picture will be used as \'billboard\' image on the product page.' => 'Tr&aelig;k og smid billeder eller klik p&aring; kassen for at starte med at uploade. Du kan sortere dine billeder ved at tr&aelig;kke uploade billeder rundt. Det f&oslash;rste billede bliver dit hovedbillede.',
    'Edit' => '&aelig;ndre',
    'Filter' => 'Filter',
    'Having trouble setting the right price for your product? We can suggest one if you know the new price of the item:' => 'Har du problemer med at s&aelig;tte den rigtige pris for dit produkt? Vi kan foresl&aring; dig ind baseret p&aring; nyprisen:',
    'How can you describe your item, in one catchy title?' => 'Hvordan kan du beskrive tingen i en fangende titel?',
    'How much is the item used? What do you enjoy so much about it? What parent-child moments did you experience with this item?' => 'Hvor brugt er udstyret? Hvor glad er du for det? Har du nogle gode historier med det?',
    'Listings' => 'Listings',
    'Location' => 'Lokalitet',
    'Manage the item you\'d like to share with other families' => 'F&aring; styr p&aring; de ting du vil dele med andre familier',
    'New price in DKK' => 'Nypris i DKK',
    'Only the weekly price is required.' => 'Kun den ugentlige pris beh&oslash;ves.',
    'Pending Requests' => 'Afventende anmodning',
    'Per day' => 'Per dag',
    'Per month' => 'Per m&aring;ned',
    'Per week' => 'Per uge',
    'Pictures' => 'Billeder',
    'Please complete your {0}.' => 'F&aelig;rdigg&oslash;r venligst din {0}.',
    'Please set your location in your {0}.' => 'V&aelig;r venlig at s&aelig;tte din lokalitet i dine {0}.',
    'Preview & Publishing' => 'Se og publiser',
    'Price' => 'Pris',
    'Price suggestions' => 'Pris forslag',
    'Pricing info' => 'Prisinformation',
    'Product info' => 'Produkt info',
    'Publish' => 'Publiser',
    'Publish date' => 'Dato for publisering',
    'Published' => 'Publiseret',
    'Receive date' => 'Afhentningsdato',
    'Rented by {0} between {1} and {2}' => 'Lejet af {0} mellem {1} og {2}',
    'Respond' => 'Responder',
    'Return date' => 'Afleveringsdato',
    'Search' => 'S&oslash;g',
    'Special' => 'Special',
    'There are some things left to be fixed before you can preview or publish this item.' => 'Der er nogle f&aring; ting tilbage som skal fikses f&oslash;r du kan se eller publisere denne ting.',
    'This is a list of your published and unpublished listings' => 'Dette er en liste af dine publiseret og ikke publiseret ting.',
    'This is a preview. Go here {0} to publish this item.' => 'Dette er en pr&oslash;ve. G&aring; her {0} for at publisere.',
    'Title' => 'Titel',
    'Unpublish' => 'Upublicer',
    'Unpublished' => 'Upubliceret',
    'View' => 'Se',
    'What are you looking for?' => 'Hvad kigger du efter?',
    'What categories describe your item best?' => 'Hvilken kategori beskriver bedst tingen?',
    'Which ages is this product ment for?' => 'Hvilke aldre er dette produkt tilt&aelig;nkt?',
    'day' => 'dag',
    'items' => 'ting',
    'link' => 'link',
    'location settings' => 'lokalitetsindstillinger',
    'month' => 'm&aring;ned',
    'profile' => 'Profil',
    'step 1 out of 2' => 'Skridt 1 ud af 2',
    'step 2 out of 2' => 'Skridt 2 ud af 2',
    'week' => 'a',
];
