<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Hi ' => '@@Hej@@',
    'All the best - ' => '@@De bedste hilsner@@',
    'And let\'s just keep this between you and me.' => '@@Og lad os bare holde det mellem dig og mig.@@',
    'And yet again - WELCOME to KidUp!' => '@@Og endnu engang - VELKOMMEN til KidUp!@@',
    'Check it out at this link: ' => '@@Tjek det ud p&aring; det her link:@@',
    'Check it out at {0}.' => '@@Tjek det ud p&aring; {0}@@',
    'Excited greetings,' => '@@Sp&aelig;ndte hilsner,@@',
    'Have you planed a pickup destination and time yet? Otherwise you guys should write each other and plan!' => '@@Har i planlagt en opsamlingsadresse og et tidspunkt? Hvis ikke, s&aring; kan i p&aring; KidUp skrive til hinanden og planl&aelig;gge tidspunktet!@@',
    'Hi ' => '@@Hej@@',
    'Hope that you had a pleasant experience and feel free to contact me.' => '@@H&aring;ber at det har v&aelig;ret en god oplevelse og v&aelig;r mere end velkommen til at kontakte mig.@@',
    'How is that for a good piece of news? You are now ready to contact {user} and plan a pickup time and adress.' => '@@Wow det er en god nyhed. Du er nu klar til at kontakte {user} og planl&aelig;gge et tidspunkt og et sted for opsamling.@@',
    'I am just writing to you to check up on the new emailadress you registered on KidUp.' => '@@Jeg skriver bare til dig for at tjekke at det her er den nye emailadresse du har registeret p&aring; KidUp.@@',
    'I heard you lost your password, do not worry! I found it.' => '@@Jeg har h&oslash;rt at du har tabt dit kodeord, bare rolig! Jeg har fundet det.@@',
    'I just checked with your accountant and the payment went through!' => '@@Jeg har lige tjekket med vores regnskabsafdeling og betalingen gik igennem!@@',
    'If any problems occur, do not hestitate to mail me at ' => '@@Hvis der opst&aring;r nogle problemer, s&aring; skal du endelig kontakte mig@@',
    'If there is anything, maybe you just want to tell me a story, then write me at : ' => '@@Hvis der er noget, m&aring;ske du bare har lyst til at fort&aelig;lle en historie, s&aring; skriv til mig p&aring; : @@',
    'If you haven\'t ordered that the KidUp user should chance into this mailadress, just leave this mail behind.' => '@@Hvis du ikke har bestilt denne mail, s&aring; skal du bare ignorere at vi har skrevet til dig.@@',
    'If you like to respond to <strong>{user}</strong> then please follow this link:' => '@@Hvis du gerne vil svare <strong>{user}</strong>  s&aring; skal du bare klikke p&aring; det her link:@@',
    'If you plan on returning it, remember to plan with {owner} for a place to deliver it back!' => '@@Hvis du planl&aelig;gger at returnere tingen, s&aring; husk at planl&aelig;gge det med {owner}!@@',
    'If you\'d like to stop the rent, remember to contact {renter} to agree on a delivery time!' => '@@Hvis du vil stoppe lejeaftalen skal du huske at kontakte {renter} og blive enige om et tilbageleveringstidspunkt!@@',
    'If your basement is filled with unused kidsstuff you can also rent it out here, so other parents - almost as sweet
    as you - can benefit from it!' => '@@Hvis din k&aelig;lder er fyldt med ubrugte b&oslash;rneting, s&aring; kan du ogs&aring; leje dem ud her, s&aring; andre for&aelig;ldre - n&aelig;sten liges&aring; s&oslash;de som dig - kan benytte sig af dem!@@',
    'Is this it? If I miraculously got it right then yay me. Oh and please click ' => '@@Er det her mailen? Hvis jeg mirakul&oslash;st ramte rigtigt s&aring;, yay mig! Og klik venligst p&aring; det her bekr&aelig;ftigelseslink:@@',
    'It seems to me that you\'re happy with it, if so you could consider contacting
            <strong>{owner}</strong> to hear if {owner, select, female{she} male{he} other{(s)he}}
            would like to rent it out again.' => '@@Det virker som om at du har v&aelig;ret glad for det, hvis det er rigtigt kan du jo skrive til <strong>{owner}</strong> for at h&oslash;re om {owner, select, female{hun} male{han} other{de}} vil leje det ud igen.@@',
    'It seems to me that {renter} is happy with it, you could consider contacting
            <strong>{renter}</strong> to hear if {renter, select, female{she} male{he} other{(s)he}}
            would like to rent it from you again.' => '@@Det virker som om at {renter} er glad for det, du kunne overveje at skrive til {owner, select, female{hende} male{ham} other{dem}} for at h&oslash;re om {owner, select, female{hun} male{han} other{de}} vil leje det igen.@@',
    'It\'s me, {0}. I just wanted to let you know that there is under 48 hours until the rent of <strong>{1}</strong>
    expires.' => '@@Det er mig, {0}. Jeg vil bare lige sige at der er under 48 timer til at lejen af <strong>{1}</strong> udl&oslash;ber.@@',
    'Just to let you know, the rent for <strong>{0}</strong> has changed into status<strong>{1}</strong>.' => '@@Bare lige for at fort&aelig;lle det, s&aring; har statusen af <strong>{0}</strong> &aelig;ndret sig til <strong>{1}</strong>@@',
    'KidUp recovery' => '@@KidUp Recovery@@',
    'KidUp user {0} wants to rent your item!' => '@@KidUp brugeren {0} vil leje din ting!@@',
    'Kidup email confirmation' => '@@KidUp mail bekr&aelig;ftigelse@@',
    'Kidup email reconfirmation' => '@@KidUp mail genbekr&aelig;ftigelse@@',
    'Kidup payment confirmation' => '@@KidUp betalings bekr&aelig;ftigelse@@',
    'Kidup: one of your rents changed' => '@@KidUp: En af dine udlejlninger er &aelig;ndret@@',
    'Kidup: one of your rents is about to end' => '@@KidUp: En af dine udlejninger er ved at v&aelig;re slut@@',
    'Kidup: one of your rents is about to start' => '@@KidUp: En af dine udlejninger er ved at starte@@',
    'Lots of Love' => '@@Barnlige hilsner@@',
    'Lots of Love,' => '@@Barnlige hilsner@@',
    'Lots of Love, ' => '@@Barnlige hilsner@@',
    'Lots of love,' => '@@Barnlige hilsner@@',
    'Lots of love, ' => '@@Barnlige hilsner@@',
    'Maybe you want to rent some stuff for your sweet children? You can do that here:' => '@@M&aring;ske du ville leje noget til dine s&oslash;de b&oslash;rn? Det kan du g&oslash;re her:@@',
    'Oh, and you can directly confirm this email adress by clicking this link: ' => '@@N&aring;eh ja, du kan bekr&aelig;fte mailen direkte, ved at klikke dette link:@@',
    'There has been quite the activity in your chat, actually <strong>{0}</strong> people wrote you during the last day.' => '@@Der har v&aelig;ret masser aktivitet i din chat, faktisk har <strong>{0}</strong> personer skrevet til dig, siden i g&aring;r.@@',
    'We are glad that you are using KidUp, if you would like to, you could share your love for sharing (silly eh\') on
    Facebook!' => '@@Vi er glade for at du bruger KidUp, hvis du vil, kan du dele din gl&aelig;de for at dele (haha) p&aring; Facebook!@@',
    'We are so excited to let you know that the rent of the item <strong>{item}</strong>
            from <strong>{owner}</strong> to you is about to start!' => '@@Jeg er vildt glad for at fort&aelig;lle dig at lejen af <strong>{item}</strong> fra <strong>{user}</strong> er t&aelig;t p&aring; at begynde!@@',
    'We are so excited to let you know that the renting of your item <strong>{item}</strong>
            to <strong>{renter}</strong> is about to start!' => '@@Jeg er vildt glad for at fort&aelig;lle dig at lejen af <strong>{item}</strong> til <strong>{renter}</strong> er t&aelig;t p&aring; at begynde@@',
    'Welcome to KidUp!' => '@@Velkommen til KidUp!@@',
    'Welcome to KidUp, I am so glad that you joined us and cannot wait to let you use our service!' => '@@Velkommen til KidUp, jeg er s&aring; glad for at du har valgt at blive medlem og kan ikke vente til at lade dig bruge vores service!@@',
    'You can do that, just by pressing this link: ' => '@@Det kan du g&oslash;re, blot ved at trykke p&aring; det her link:@@',
    'You can recover it by visiting' => '@@Du kan f&aring; det tilbage ved at bes&oslash;ge@@',
    'You have {0} unread messages at KidUp' => '@@Du har {0} ul&aelig;ste beskeder p&aring; KidUp@@',
    'Your item {0} has been seen by a lot of people and one of them, <strong>{1}</strong>, decided to ask
    to rent it.' => '@@Din ting {0} er blevet set af mange mennesker, <strong>{1}</strong> har besluttet sig for at om en lejeaftale.@@',
    'create new item' => '@@Opret ny ting@@',
    'here.' => '@@Her.@@',
    '{user} would like to rent if from <strong>{date_from, date}</strong>till <strong>{date_to, date}</strong> which would give
    you a total of <strong>{amount, number}.</strong> You can learn more about {user} ' => '@@{user} vil gerne leje den fra d. <strong>{date_from, date}</strong> til d. <strong>{date_to, date}</strong> hvilket vil give dig <strong>{amount, number}.</strong>. Du kan l&aelig;re mere omkring {user} her: @@',
    'Change email preferences' => 'Skift emailpr&aelig;ferencer',
    'Click here to read this mail in your browser' => 'Klik her for at l&aelig;se denne mail i din browser',
    'Click {0} to see the details of this booking' => 'Klik {0} for at se detaljerne omkring denne booking',
    'Go to conversation' => 'G&aring; til samtalen',
    'Hi {1}, {0} sent you a message.' => 'Hej {1}, {0} har sendt dig en meddelelse. ',
    'KidUp Social' => 'KidUp Social',
    'KidUp recovery request' => 'KidUp gendannelse anmodning',
    'Password recovery' => 'Gendan Kodeord',
    'Please click the following button to set a new password:' => 'Klik venligst p&aring; den f&oslash;lgende knap for at lave et nyt kodeord:',
    'You can view the details of the booking {0}' => 'Du kan se detaljerne omkring denne bookin {0}',
    'You\'ve requested a password recovery on KidUp, and here it is!' => 'Du har bedt om vi genskabte dit kodeord p&aring; KidUp, og her er det!',
    'here' => 'her',
];
