<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No reviews yet' => 'Ingen reviews endnu',
    'Accuracy' => 'Nøjagtighed',
    'By {0}' => 'Med {0}',
    'Communication' => 'Kommunikation',
    'Describe your experience' => 'Beskriv din oplevelse',
    'Exchange' => 'Overleveringen',
    'For KidUp' => 'For KidUp',
    'Handling' => 'Håndtering',
    'How did the exchange of product go?' => 'Hvordan gik overleveringen af produktet? ',
    'How did the renter treat the product, was it returned in the same state as it was rented out?' => 'Hvordan behandlede lejeren produktet? Blevet det returneret i god stand?',
    'How easy was it to communicate with the owner?' => 'Hvor nemt var det at kommunikere med ejeren?',
    'How well did the photo\'s and description describe the actual item?' => 'Hvor godt beskrev billederne og beskrivelse det faktiske produkt?',
    'Is there anything you\'d like to tell to KidUp regarding this experience?' => 'Er der noget som du vil fortælle KidUp, omkring denne oplevelse?',
    'Overall Experience' => 'Totale Oplevelse',
    'Private feedback to {0}' => 'Privat feedback til {0}',
    'Rate & Review' => 'Bedøm',
    'Submit Review' => 'Send bedømmelse',
    'Thank you for reviewing!' => 'Tak for bedømmelsen!',
    'This feedback will only be visible to the owner of the item.' => 'Feedbacken vil kun være synlig for ejeren af produktet.',
    'This review will be public.' => 'Bedømmelsen vil være offentlig.',
];
