<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account settings' => '@@Brugerindstillinger@@',
    'Contact us' => '@@Kontakt Os@@',
    'Email settings' => '@@Email indstillinger@@',
    'Item Availability' => '@@Genstandens tilg&aelig;nlighed@@',
    'Item Details' => '@@Detaljer@@',
    'Item Prices' => '@@Priss&aelig;tning@@',
    'Item Rents' => '@@Lejeaftaler@@',
    'Item images' => '@@Ting@@',
    'List Your Rents' => '@@List dine lejeaftaler@@',
    'My items list' => '@@Mine ting@@',
    'Profile verification' => '@@Profil verifikation@@',
    'Resend confirmation email' => '@@Gensend bekr&aelig;ftelsesmail@@',
    'View For Item {0}' => '@@Se tingene for {0}@@',
    'Your kidup wallet' => '@@Din KidUp pung@@',
    'About our company' => 'Omkring Os',
    'Account Settings' => 'Brugerindstillinger',
    'Admin' => 'Admin',
    'Chat' => 'Chat',
    'Complete your registration' => 'Fuldf&oslash;r din registrering',
    'Confirm Your Rent' => 'Bekr&aelig;ft din lejeaftale',
    'Confirm your telephone' => 'Bekr&aelig;ft din telefon',
    'Connect your account to {0}' => 'Forbind din bruger til {0}',
    'Error' => 'Fejl',
    'Frequently asked questions' => 'Oftest stillede sp&oslash;rgsm&aring;l',
    'How do payments work' => 'Hvordan fungerer betalingen',
    'How to rent from other parents' => 'Hvordan lejer jeg fra andre for&aelig;ldre',
    'How to rent to other parents' => 'Hvordan udlejer jeg til andre for&aelig;ldre',
    'KidUp guides' => 'KidUp guides',
    'Kidup user {0}' => 'KidUp bruger {0}',
    'Launching soon' => 'Er snart i luften',
    'Location Settings' => 'Lokalitetsindstillinger',
    'Log In' => 'Login',
    'Online parent-to-parent marketplace' => 'Online for&aelig;ldre-til-for&aelig;ldre markedsplads',
    'Payout Preference' => 'Udbetalingsindstillinger',
    'Privacy' => 'Privathed',
    'Profile settings' => 'Profilindstillinger',
    'Recover your password' => 'Har du glemt dit kodeord?',
    'Respond to booking request' => 'Svar p&aring; booking foresp&oslash;rgsler',
    'Safety' => 'Sikkerhed',
    'Share Kid Stuff' => 'Del dine b&oslash;rneting',
    'Sign up' => 'Opret profil',
    'Terms and conditions' => 'Terms and Conditions',
    'Thank you for signing up' => 'Tak fordi du oprettede en bruger',
    'Trust and Verification' => 'Tillid og Verifikation',
    'Why use kidup' => 'Hvorfor bruge KidUp',
    'Your Current Bookings' => 'Dine nuv&aelig;rende bookings',
    'Your Items' => 'Dine produkter',
    'Your Previous Bookings' => 'Dine tidligere bookings',
    'reset your password' => 'Reset dit kodeord',
    '{0}' => '{0}',
    '{0} KidStuff' => '{0} B&oslash;rneting',
];
