<?php

$urls = [
//    '/' => 'home/home',
    '/' => 'home/home/fake-home',
    'home' => 'home/home',
    'change-language' => 'home/change-language',
    'super-secret-cache-flush' => 'home/super-secret-cache-flush',
    'search' => 'search/search',
    'search/<query>' => 'search/search',
    'login' => 'user/security/login',
    'site/login' => 'user/security/login',
    'user/login' => 'user/security/login',
    'user/register' => 'user/registration/register',
    'logout' => 'user/security/logout',
    'user/logout' => 'user/security/logout',
    'user/<id:\d+>' => 'user/profile/show',
    'item/<id:\d+>' => 'item/view/index',
    'item/search' => 'item/search/index',
    'item/create' => 'item/create/index',
    'item/<id:\d+>/edit' => 'item/create/edit',
    'item/<id:\d+>/publish' => 'item/create/publish',
    'item/<id:\d+>/unpublish' => 'item/create/unpublish',
    'item/<id:\d+>/bookings' => 'item/list/bookings',
    'booking/<id:\d+>' => 'booking/view/index',
    'booking/confirm' => 'booking/default/confirm',
    'booking/current' => 'booking/list/current',
    'booking/previous' => 'booking/list/previous',
    'booking/by-item/<id:\d+>' => 'booking/list/by-item',
    'booking/<id:\d+>/receipt' => 'booking/view/receipt',
    'booking/<id:\d+>/invoice' => 'booking/view/invoice',
    'booking/<id:\d+>/request' => 'booking/default/request',
    'booking/<id:\d+>/conversation' => 'booking/default/conversation',
    'mail/show/<mail>' => 'notification/view/test',
    'mail/overview' => 'notification/view/overview',
    'mail/click' => 'notification/view/link',
    'mail/<id>' => 'notification/view/index',
    'mail/view/test' => 'notification/view/test',
    'sendgrid/webhook-apqcbec' => 'notification/sendgrid/webhook-apqcbec', // sendgrid incomming webhook
    'review/create/<bookingId:\d+>' => 'review/create/index',
    'inbox/<id:\d+>' => 'message/chat/conversation',
    'inbox' => 'message/chat/inbox',
    'conversation/<id:\d+>' => 'message.conversation',
    'p/<page>' => 'pages/default/wordpress',
    'p/<page>/<view>' => 'pages/default/<page>',
   
];

return $urls;