<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-08-26 20:06:29
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@app/web/release-assets',
        'baseUrl' => '@web/release-assets',
        'js' => [
            'js/all-2396d70c0abc7361fdad3e3ed6b6a26b.js',
        ],
        'css' => [
            'css/all-2fc44b4c5cb9d99898c980d7565b37c3.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\JQueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\web\\JQueryAsset',
            'app\\assets\\FontAwesomeAsset',
            'all',
        ],
    ],
    '\\yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\modules\\home\\assets\\HomeAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            '\\yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\modules\\booking\\assets\\ConfirmAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    '\\yii\\jui\\JuiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    '\\app\\assets\\DropZoneAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\modules\\item\\assets\\CreateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            '\\yii\\web\\JqueryAsset',
            '\\yii\\jui\\JuiAsset',
            '\\app\\assets\\DropZoneAsset',
            'all',
        ],
    ],
    'app\\modules\\item\\assets\\ListAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\modules\\item\\assets\\MenuSearchAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\modules\\item\\assets\\ViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\modules\\message\\assets\\MessageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\modules\\pages\\assets\\WpAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    '\\app\\assets\\AngularAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    '\\yii\\widgets\\PjaxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'all',
        ],
    ],
    'app\\modules\\search\\assets\\ItemSearchAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            '\\app\\assets\\AngularAsset',
            '\\yii\\web\\JqueryAsset',
            '\\yii\\jui\\JuiAsset',
            '\\yii\\widgets\\PjaxAsset',
            'all',
        ],
    ],
    'app\\modules\\user\\assets\\ProfileAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\modules\\user\\assets\\SettingsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
];