<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-09-16 20:07:37
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@app/web/release-assets',
        'baseUrl' => '@web/release-assets',
        'js' => [
            'js/all-c44925958b65f13b74122790c3d005de.js',
        ],
        'css' => [
            'css/all-244703a8eb3df9b4a83c72cb9e1892fb.css',
        ],
    ],
    'app\\assets\\GsdkAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
];